version: "3.8"

services:
  api:
    build:
      context: .
      target: dev
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - ./src:/app/src
      - ./.uploads:/app/.uploads
